openapi: 3.0.1
info:
  contact:
    email: info@flowpipe.io
    name: Flowpipe
    url: http://www.flowpipe.io
  description: Flowpipe is workflow and pipelines for DevSecOps.
  license:
    name: AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  title: Flowpipe
  version: 0.1.0
servers:
- url: https://localhost/api/v0
paths:
  /pipeline:
    get:
      description: Lists pipelines
      operationId: pipeline_list
      parameters:
      - description: "The max number of items to fetch per page of data, subject to\
          \ a min and max of 1 and 100 respectively. If not specified will default\
          \ to 25."
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 25
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: "When list results are truncated, next_token will be returned,\
          \ which is a cursor to fetch the next page of data. Pass next_token to the\
          \ subsequent list request to fetch the next page of data."
        explode: true
        in: query
        name: next_token
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPipelineResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: List pipelines
      tags:
      - Pipeline
  /pipeline/{pipeline_name}:
    get:
      description: Get pipeline
      operationId: pipeline_get
      parameters:
      - description: The name of the pipeline
        explode: false
        in: path
        name: pipeline_name
        required: true
        schema:
          format: "^[a-z_]{0,32}$"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Not Found
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: Get pipeline
      tags:
      - Pipeline
  /pipeline/{pipeline_name}/cmd:
    post:
      operationId: pipeline_cmd
      parameters:
      - description: The name of the pipeline
        explode: false
        in: path
        name: pipeline_name
        required: true
        schema:
          format: "^[a-z_]{0,32}$"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CmdPipeline'
        description: Pipeline command.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunPipelineResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Not Found
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: Execute a pipeline command
      tags:
      - Pipeline
      x-codegen-request-body-name: request
  /process:
    get:
      description: Lists processs
      operationId: process_list
      parameters:
      - description: "The max number of items to fetch per page of data, subject to\
          \ a min and max of 1 and 100 respectively. If not specified will default\
          \ to 25."
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 25
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: "When list results are truncated, next_token will be returned,\
          \ which is a cursor to fetch the next page of data. Pass next_token to the\
          \ subsequent list request to fetch the next page of data."
        explode: true
        in: query
        name: next_token
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListProcessResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: List processs
      tags:
      - Process
  /process/{process_id}:
    get:
      description: Get process
      operationId: process_get
      parameters:
      - description: The name of the process
        explode: false
        in: path
        name: process_id
        required: true
        schema:
          format: "^[a-z]{0,32}$"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/execution.Execution'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Not Found
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: Get process
      tags:
      - Process
  /process/{process_id}/output:
    get:
      description: Get process output
      operationId: process_get_output
      parameters:
      - description: The name of the process
        explode: false
        in: path
        name: process_id
        required: true
        schema:
          format: "^[a-z]{0,32}$"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputData'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Not Found
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: Get process output
      tags:
      - Process
  /trigger:
    get:
      description: Lists triggers
      operationId: trigger_list
      parameters:
      - description: "The max number of items to fetch per page of data, subject to\
          \ a min and max of 1 and 100 respectively. If not specified will default\
          \ to 25."
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 25
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: "When list results are truncated, next_token will be returned,\
          \ which is a cursor to fetch the next page of data. Pass next_token to the\
          \ subsequent list request to fetch the next page of data."
        explode: true
        in: query
        name: next_token
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListTriggerResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: List triggers
      tags:
      - Trigger
  /trigger/{trigger_name}:
    get:
      description: Get trigger
      operationId: trigger_get
      parameters:
      - description: The name of the trigger
        explode: false
        in: path
        name: trigger_name
        required: true
        schema:
          format: "^[a-z]{0,32}$"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trigger'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Not Found
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: Get trigger
      tags:
      - Trigger
  /variable:
    get:
      description: Lists variables
      operationId: variable_list
      parameters:
      - description: "The max number of items to fetch per page of data, subject to\
          \ a min and max of 1 and 100 respectively. If not specified will default\
          \ to 25."
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 25
          maximum: 100
          minimum: 1
          type: integer
        style: form
      - description: "When list results are truncated, next_token will be returned,\
          \ which is a cursor to fetch the next page of data. Pass next_token to the\
          \ subsequent list request to fetch the next page of data."
        explode: true
        in: query
        name: next_token
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListVariableResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: List variables
      tags:
      - Variable
  /variable/{variable_name}:
    get:
      description: Get variable
      operationId: variable_get
      parameters:
      - description: The name of the variable
        explode: false
        in: path
        name: variable_name
        required: true
        schema:
          format: "^[a-z]{0,32}$"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Variable'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Not Found
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fperr.ErrorModel'
          description: Internal Server Error
      summary: Get variable
      tags:
      - Variable
components:
  schemas:
    CmdPipeline:
      example:
        command: run
      properties:
        command:
          enum:
          - run
          type: string
      required:
      - command
      type: object
    Input:
      type: object
    ListPipelineResponse:
      example:
        next_token: next_token
        items:
        - outputs:
          - depends_on:
            - depends_on
            - depends_on
            name: name
            sensitive: true
            value: "{}"
            resolved: true
          - depends_on:
            - depends_on
            - depends_on
            name: name
            sensitive: true
            value: "{}"
            resolved: true
          name: name
          description: description
          steps:
          - "{}"
          - "{}"
        - outputs:
          - depends_on:
            - depends_on
            - depends_on
            name: name
            sensitive: true
            value: "{}"
            resolved: true
          - depends_on:
            - depends_on
            - depends_on
            name: name
            sensitive: true
            value: "{}"
            resolved: true
          name: name
          description: description
          steps:
          - "{}"
          - "{}"
      properties:
        items:
          items:
            $ref: '#/components/schemas/Pipeline'
          type: array
        next_token:
          type: string
      type: object
    ListProcessResponse:
      example:
        next_token: next_token
        items:
        - process_id: process_id
        - process_id: process_id
      properties:
        items:
          items:
            $ref: '#/components/schemas/Process'
          type: array
        next_token:
          type: string
      type: object
    ListTriggerResponse:
      example:
        next_token: next_token
        items:
        - name: name
          type: type
        - name: name
          type: type
      properties:
        items:
          items:
            $ref: '#/components/schemas/Trigger'
          type: array
        next_token:
          type: string
      type: object
    ListVariableResponse:
      example:
        next_token: next_token
        items:
        - name: name
          type: type
        - name: name
          type: type
      properties:
        items:
          items:
            $ref: '#/components/schemas/Variable'
          type: array
        next_token:
          type: string
      type: object
    NextStepAction:
      enum:
      - start
      - inaccessible
      - skip
      type: string
      x-enum-varnames:
      - NextStepActionStart
      - NextStepActionInaccessible
      - NextStepActionSkip
    Output:
      properties:
        data:
          type: object
        errors:
          items:
            $ref: '#/components/schemas/StepError'
          type: array
        status:
          type: string
      type: object
    OutputData:
      type: object
    Pipeline:
      example:
        outputs:
        - depends_on:
          - depends_on
          - depends_on
          name: name
          sensitive: true
          value: "{}"
          resolved: true
        - depends_on:
          - depends_on
          - depends_on
          name: name
          sensitive: true
          value: "{}"
          resolved: true
        name: name
        description: description
        steps:
        - "{}"
        - "{}"
      properties:
        description:
          type: string
        name:
          type: string
        outputs:
          items:
            $ref: '#/components/schemas/PipelineOutput'
          type: array
        steps:
          items:
            type: object
          type: array
      type: object
    PipelineOutput:
      example:
        depends_on:
        - depends_on
        - depends_on
        name: name
        sensitive: true
        value: "{}"
        resolved: true
      properties:
        depends_on:
          items:
            type: string
          type: array
        name:
          type: string
        resolved:
          type: boolean
        sensitive:
          type: boolean
        value:
          type: object
      type: object
    Process:
      example:
        process_id: process_id
      properties:
        process_id:
          type: string
      type: object
    RunPipelineResponse:
      example:
        execution_id: execution_id
        pipeline_execution_id: pipeline_execution_id
        parent_step_execution_id: parent_step_execution_id
      properties:
        execution_id:
          type: string
        parent_step_execution_id:
          type: string
        pipeline_execution_id:
          type: string
      type: object
    StepError:
      example:
        pipeline: pipeline
        pipeline_execution_id: pipeline_execution_id
        step_execution_id: step_execution_id
        error_code: 0
        step: step
        message: message
      properties:
        error_code:
          type: integer
        message:
          type: string
        pipeline:
          type: string
        pipeline_execution_id:
          type: string
        step:
          type: string
        step_execution_id:
          type: string
      type: object
    StepForEach:
      properties:
        for_each_output:
          $ref: '#/components/schemas/Output'
        for_each_total_count:
          type: integer
        index:
          type: integer
      required:
      - for_each_total_count
      - index
      type: object
    Trigger:
      example:
        name: name
        type: type
      properties:
        name:
          type: string
        type:
          type: string
      type: object
    Variable:
      example:
        name: name
        type: type
      properties:
        name:
          type: string
        type:
          type: string
      type: object
    execution.Execution:
      example:
        pipeline_executions:
          key:
            args: "{}"
            parent_step_execution_id: parent_step_execution_id
            pipeline_output: "{}"
            name: name
            id: id
            parent_execution_id: parent_execution_id
            errors:
            - pipeline: pipeline
              pipeline_execution_id: pipeline_execution_id
              step_execution_id: step_execution_id
              error_code: 0
              step: step
              message: message
            - pipeline: pipeline
              pipeline_execution_id: pipeline_execution_id
              step_execution_id: step_execution_id
              error_code: 0
              step: step
              message: message
            step_executions:
              key:
                output: null
                step_for_each: null
                input: "{}"
                pipeline_execution_id: pipeline_execution_id
                name: name
                id: id
                next_step_action: null
                status: status
            status: status
        id: id
      properties:
        id:
          description: Unique identifier for this execution.
          type: string
        pipeline_executions:
          additionalProperties:
            $ref: '#/components/schemas/execution.PipelineExecution'
          description: |-
            Pipelines triggered by the execution. Even if the pipelines are nested,
            we maintain a flat list of all pipelines for easy lookup and querying.
          type: object
      type: object
    execution.PipelineExecution:
      example:
        args: "{}"
        parent_step_execution_id: parent_step_execution_id
        pipeline_output: "{}"
        name: name
        id: id
        parent_execution_id: parent_execution_id
        errors:
        - pipeline: pipeline
          pipeline_execution_id: pipeline_execution_id
          step_execution_id: step_execution_id
          error_code: 0
          step: step
          message: message
        - pipeline: pipeline
          pipeline_execution_id: pipeline_execution_id
          step_execution_id: step_execution_id
          error_code: 0
          step: step
          message: message
        step_executions:
          key:
            output: null
            step_for_each: null
            input: "{}"
            pipeline_execution_id: pipeline_execution_id
            name: name
            id: id
            next_step_action: null
            status: status
        status: status
      properties:
        args:
          allOf:
          - $ref: '#/definitions/Input'
          description: The input to the pipeline
          type: object
        errors:
          items:
            $ref: '#/components/schemas/StepError'
          type: array
        id:
          description: Unique identifier for this pipeline execution
          type: string
        name:
          description: The name of the pipeline
          type: string
        parent_execution_id:
          type: string
        parent_step_execution_id:
          description: "If this is a child pipeline, then track it's parent"
          type: string
        pipeline_output:
          description: The output of the pipeline
          properties: {}
          type: object
        status:
          description: "The status of the pipeline execution: queued, planned, started,\
            \ completed, failed"
          type: string
        step_executions:
          additionalProperties:
            $ref: '#/components/schemas/execution.StepExecution'
          description: Steps triggered by pipelines in the execution.
          type: object
      type: object
    execution.StepExecution:
      example:
        output: null
        step_for_each: null
        input: "{}"
        pipeline_execution_id: pipeline_execution_id
        name: name
        id: id
        next_step_action: null
        status: status
      properties:
        id:
          type: string
        input:
          allOf:
          - $ref: '#/definitions/Input'
          description: Input to the step
          type: object
        name:
          description: The name of the step in the pipeline definition
          type: string
        next_step_action:
          $ref: '#/components/schemas/NextStepAction'
        output:
          $ref: '#/components/schemas/execution_StepExecution_output'
        pipeline_execution_id:
          description: Unique identifier for this step execution
          type: string
        status:
          description: "The status of the step execution: \"started\", \"finished\"\
            , \"failed\", \"skipped\""
          type: string
        step_for_each:
          $ref: '#/components/schemas/execution_StepExecution_step_for_each'
      type: object
    fperr.ErrorDetailModel:
      properties:
        location:
          type: string
        message:
          type: string
      type: object
    fperr.ErrorModel:
      properties:
        detail:
          type: string
        instance:
          type: string
        retryable:
          description: All errors are fatal unless specified
          type: boolean
        status:
          type: integer
        title:
          type: string
        type:
          type: string
        validation_errors:
          items:
            $ref: '#/components/schemas/fperr.ErrorDetailModel'
          type: array
      required:
      - instance
      - status
      - title
      - type
      type: object
    execution_StepExecution_output:
      allOf:
      - $ref: '#/definitions/Output'
      description: Output of the step
      type: object
    execution_StepExecution_step_for_each:
      allOf:
      - $ref: '#/definitions/StepForEach'
      description: for_each controls
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
